import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../core/constants.dart';
import '../../core/theme.dart';
import '../../models/attendance_model.dart';
import '../../models/class_model.dart';
import '../../models/user_model.dart';
import '../../services/firestore_service.dart';

class AttendanceReportScreen extends StatefulWidget {
  final String classId;
  const AttendanceReportScreen({super.key, required this.classId});

  @override
  State<AttendanceReportScreen> createState() => _AttendanceReportScreenState();
}

class _AttendanceReportScreenState extends State<AttendanceReportScreen> {
  ClassModel? _classModel;
  List<AttendanceModel> _allAttendance = [];
  List<UserModel> _enrolledStudentDocs = [];
  List<String> _sessionDates = [];
  String? _selectedDate;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    try {
      final classDoc = await FirestoreService().getStudentClasses([
        widget.classId,
      ]);
      if (classDoc.isEmpty) return;
      _classModel = classDoc.first;

      _allAttendance = await FirestoreService().getAttendanceForClass(
        widget.classId,
      );

      final studentDocs = await Future.wait(
        _classModel!.enrolledStudents.map(
          (id) => FirestoreService().getUser(id),
        ),
      );
      _enrolledStudentDocs = studentDocs.whereType<UserModel>().toList();

      _sessionDates = _allAttendance.map((a) => a.sessionDate).toSet().toList()
        ..sort((a, b) => b.compareTo(a));

      _selectedDate = _sessionDates.isNotEmpty ? _sessionDates.first : null;
    } catch (e) {
      debugPrint(e.toString());
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  List<AttendanceModel> get _presentRecords =>
      _allAttendance.where((a) => a.sessionDate == _selectedDate).toList();

  Set<String> get _presentIds =>
      _presentRecords.map((r) => r.studentId).toSet();

  List<UserModel> get _absentStudents =>
      _enrolledStudentDocs.where((s) => !_presentIds.contains(s.id)).toList();

  int get _percent => _enrolledStudentDocs.isEmpty
      ? 0
      : (_presentRecords.length / _enrolledStudentDocs.length * 100).round();

  Future<void> _exportPdf() async {
    final doc = pw.Document();
    final present = _presentRecords;
    final absent = _absentStudents;

    doc.addPage(
      pw.MultiPage(
        build: (ctx) => [
          pw.Text(universityName, style: const pw.TextStyle(fontSize: 10)),
          pw.SizedBox(height: 4),
          pw.Text(
            'Attendance Report',
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
          pw.Text('${_classModel?.courseCode} — ${_classModel?.courseName}'),
          pw.Text(
            'Date: $_selectedDate   Room: ${_classModel?.location['roomName']}',
          ),
          pw.SizedBox(height: 12),
          pw.TableHelper.fromTextArray(
            context: ctx,
            headers: ['Student', 'Reg. Number', 'Status', 'Time'],
            data: [
              ...present.map(
                (r) => [
                  r.studentName,
                  r.regNumber,
                  'PRESENT',
                  DateFormat('HH:mm').format(r.timestamp),
                ],
              ),
              ...absent.map((s) => [s.name, s.regNumber, 'ABSENT', '-']),
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            'Generated by JKUAT Attend on ${DateFormat('dd MMM yyyy').format(DateTime.now())}',
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(onLayout: (_) async => doc.save());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Attendance Report'),
        actions: [
          IconButton(
            icon: const Icon(Icons.picture_as_pdf),
            onPressed: _exportPdf,
          ),
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : Column(
              children: [
                Card(
                  margin: const EdgeInsets.all(16),
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          _classModel?.courseCode ?? '',
                          style: const TextStyle(
                            fontWeight: FontWeight.bold,
                            color: primaryGreen,
                            fontSize: 18,
                          ),
                        ),
                        Text(
                          _classModel?.courseName ?? '',
                          style: const TextStyle(fontSize: 14),
                        ),
                        Row(
                          children: [
                            const Icon(
                              Icons.room,
                              size: 14,
                              color: Colors.grey,
                            ),
                            const SizedBox(width: 4),
                            Text(
                              _classModel?.location['roomName'] ?? '',
                              style: const TextStyle(color: Colors.grey),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            const Icon(
                              Icons.people,
                              size: 14,
                              color: Colors.grey,
                            ),
                            const SizedBox(width: 4),
                            Text(
                              '${_classModel?.enrolledStudents.length ?? 0} enrolled',
                              style: const TextStyle(color: Colors.grey),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
                if (_sessionDates.isEmpty)
                  const Expanded(
                    child: Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.inbox, size: 64, color: Colors.grey),
                          Text('No attendance recorded yet'),
                        ],
                      ),
                    ),
                  )
                else ...[
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16),
                    child: DropdownButton<String>(
                      isExpanded: true,
                      value: _selectedDate,
                      items: _sessionDates
                          .map(
                            (d) => DropdownMenuItem(
                              value: d,
                              child: Text('Session: $d'),
                            ),
                          )
                          .toList(),
                      onChanged: (v) => setState(() => _selectedDate = v),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16),
                    child: Text(
                      '${_presentRecords.length} present · ${_absentStudents.length} absent · $_percent%',
                      style: const TextStyle(
                        fontWeight: FontWeight.bold,
                        color: primaryGreen,
                      ),
                    ),
                  ),
                  Expanded(
                    child: SingleChildScrollView(
                      scrollDirection: Axis.horizontal,
                      child: SingleChildScrollView(
                        child: DataTable(
                          columns: const [
                            DataColumn(label: Text('Student')),
                            DataColumn(label: Text('Reg. Number')),
                            DataColumn(label: Text('Status')),
                            DataColumn(label: Text('Time')),
                          ],
                          rows: [
                            ..._presentRecords.map(
                              (r) => DataRow(
                                cells: [
                                  DataCell(Text(r.studentName)),
                                  DataCell(Text(r.regNumber)),
                                  DataCell(
                                    Chip(
                                      label: const Text(
                                        'Present',
                                        style: TextStyle(color: white),
                                      ),
                                      backgroundColor: lightGreen,
                                    ),
                                  ),
                                  DataCell(
                                    Text(
                                      DateFormat('HH:mm').format(r.timestamp),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            ..._absentStudents.map(
                              (s) => DataRow(
                                cells: [
                                  DataCell(Text(s.name)),
                                  DataCell(Text(s.regNumber)),
                                  DataCell(
                                    Chip(
                                      label: const Text(
                                        'Absent',
                                        style: TextStyle(color: white),
                                      ),
                                      backgroundColor: accentRed,
                                    ),
                                  ),
                                  const DataCell(Text('-')),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ],
              ],
            ),
    );
  }
}
